# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D8qrD1dtkXCVaEFVqUlu2aSrY3GLel4a
"""

!pip install transformers datasets rouge_score accelerate

import torch
from transformers import T5Tokenizer, T5ForConditionalGeneration
from transformers import GPT2Tokenizer, GPT2LMHeadModel
from torch.utils.data import Dataset, DataLoader
import pandas as pd
from rouge_score import rouge_scorer
from tqdm.auto import tqdm

import pandas as pd

# Read Excel file
df = pd.read_excel('train.xlsx')

# Save as CSV
df.to_csv('train.csv', index=False)

train_df = pd.read_csv('train.csv')
val_df = pd.read_csv('validation.csv')
test_df = pd.read_csv('test.csv')

class SummarizationDataset(Dataset):
    def __init__(self, dataframe, tokenizer, model_type='t5', source_max_length=512, target_max_length=150):
        self.data = dataframe
        self.tokenizer = tokenizer
        self.model_type = model_type
        self.source_max_length = source_max_length
        self.target_max_length = target_max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        article = str(self.data.iloc[idx]['article'])
        summary = str(self.data.iloc[idx]['highlights'])

        if self.model_type == 't5':
            source_encoding = self.tokenizer(article, max_length=self.source_max_length, padding='max_length', truncation=True, return_tensors="pt")
            target_encoding = self.tokenizer(summary, max_length=self.target_max_length, padding='max_length', truncation=True, return_tensors="pt")
            labels = target_encoding['input_ids']
            labels[labels == self.tokenizer.pad_token_id] = -100
            return {
                'input_ids': source_encoding['input_ids'].squeeze(),
                'attention_mask': source_encoding['attention_mask'].squeeze(),
                'labels': labels.squeeze()
            }
        elif self.model_type == 'gpt2':
            # GPT-2 doesn't have encoder, input + target concatenated (causal LM)
            input_encoding = self.tokenizer(article, max_length=self.source_max_length, truncation=True, return_tensors='pt')
            target_encoding = self.tokenizer(summary, max_length=self.target_max_length, truncation=True, return_tensors='pt')
            # For GPT2 fine-tuning, inputs are article + summary (for causal LM)
            input_ids = torch.cat([input_encoding['input_ids'], target_encoding['input_ids']], dim=1).squeeze()
            # labels equal to input_ids but ignore article tokens loss
            labels = input_ids.clone()
            labels[:input_encoding['input_ids'].size(1)] = -100  # Ignore article tokens loss
            return {
                'input_ids': input_ids,
                'attention_mask': torch.ones_like(input_ids),
                'labels': labels
            }

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# T5-small
t5_tokenizer = T5Tokenizer.from_pretrained('t5-small')
t5_model = T5ForConditionalGeneration.from_pretrained('t5-small').to(device)

# GPT-2 small
gpt2_tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
gpt2_tokenizer.pad_token = gpt2_tokenizer.eos_token  # GPT2 has no pad token
gpt2_model = GPT2LMHeadModel.from_pretrained('gpt2').to(device)

train_dataset_t5 = SummarizationDataset(train_df, t5_tokenizer, model_type='t5')
val_dataset_t5 = SummarizationDataset(val_df, t5_tokenizer, model_type='t5')

train_dataset_gpt2 = SummarizationDataset(train_df, gpt2_tokenizer, model_type='gpt2')
val_dataset_gpt2 = SummarizationDataset(val_df, gpt2_tokenizer, model_type='gpt2')

train_loader_t5 = DataLoader(train_dataset_t5, batch_size=8, shuffle=True)
val_loader_t5 = DataLoader(val_dataset_t5, batch_size=8)

train_loader_gpt2 = DataLoader(train_dataset_gpt2, batch_size=2, shuffle=True)  # smaller batch for GPT2 due to memory
val_loader_gpt2 = DataLoader(val_dataset_gpt2, batch_size=2)

def train_epoch(model, dataloader, optimizer, device):
    model.train()
    total_loss = 0
    loop = tqdm(dataloader)
    for batch in loop:
        optimizer.zero_grad()
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['labels'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        loop.set_postfix(loss=loss.item())
    return total_loss / len(dataloader)

def evaluate(model, dataloader, device):
    model.eval()
    total_loss = 0
    with torch.no_grad():
        for batch in dataloader:
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['labels'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
            loss = outputs.loss
            total_loss += loss.item()
    return total_loss / len(dataloader)

from torch.optim import AdamW
# from transformers import AdamW # Removed this line as it's causing the error

optimizer_t5 = AdamW(t5_model.parameters(), lr=3e-4)
optimizer_gpt2 = AdamW(gpt2_model.parameters(), lr=3e-5)

epochs = 3

for epoch in range(epochs):
    print(f"Epoch {epoch+1} for T5-small")
    train_loss = train_epoch(t5_model, train_loader_t5, optimizer_t5, device)
    val_loss = evaluate(t5_model, val_loader_t5, device)
    print(f"T5 Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")

    print(f"Epoch {epoch+1} for GPT-2 small")
    train_loss = train_epoch(gpt2_model, train_loader_gpt2, optimizer_gpt2, device)
    val_loss = evaluate(gpt2_model, val_loader_gpt2, device)
    print(f"GPT-2 Train Loss: {train_loss:.4f} | Val Loss: {val_loss:.4f}")

def generate_summary_t5(text, model, tokenizer, device, max_length=150):
    model.eval()
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding='max_length', max_length=512).to(device)
    summary_ids = model.generate(
        inputs['input_ids'],
        attention_mask=inputs['attention_mask'],
        max_length=max_length,
        num_beams=4,
        early_stopping=True
    )
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

def generate_summary_gpt2(text, model, tokenizer, device, max_length=150):
    model.eval()
    input_ids = tokenizer.encode(text, return_tensors='pt').to(device)
    with torch.no_grad():
        outputs = model.generate(
            input_ids,
            max_length=max_length + input_ids.shape[-1],
            pad_token_id=tokenizer.eos_token_id,
            do_sample=True,
            top_k=50,
            top_p=0.95,
            num_return_sequences=1
        )
    # Remove input prompt from output to get summary
    generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    summary = generated_text[len(text):].strip()
    return summary

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)

def evaluate_rouge(model, tokenizer, dataset, device, generate_func):
    model.eval()
    scores = {'rouge1': [], 'rouge2': [], 'rougeL': []}
    for idx in range(len(dataset)):
        article = dataset.data.iloc[idx]['Article']
        reference = dataset.data.iloc[idx]['Highlights']

        prediction = generate_func(article, model, tokenizer, device)
        rouge_scores = scorer.score(reference, prediction)
        for key in scores.keys():
            scores[key].append(rouge_scores[key].fmeasure)

    avg_scores = {key: sum(scores[key]) / len(scores[key]) for key in scores.keys()}
    return avg_scores

test_dataset_t5 = SummarizationDataset(test_df, t5_tokenizer, model_type='t5')
test_dataset_gpt2 = SummarizationDataset(test_df, gpt2_tokenizer, model_type='gpt2')

print("Evaluating T5-small on test set...")
rouge_t5 = evaluate_rouge(t5_model, t5_tokenizer, test_dataset_t5, device, generate_summary_t5)
print(rouge_t5)

print("Evaluating GPT-2 small on test set...")
rouge_gpt2 = evaluate_rouge(gpt2_model, gpt2_tokenizer, test_dataset_gpt2, device, generate_summary_gpt2)
print(rouge_gpt2)

import gradio as gr

def summarize(text, model_choice):
    if model_choice == "T5-small (Encoder-Decoder Transformer)":
        summary = generate_summary_t5(text, t5_model, t5_tokenizer, device)
    elif model_choice == "GPT-2 small (Decoder-only Transformer)":
        summary = generate_summary_gpt2(text, gpt2_model, gpt2_tokenizer, device)
    else:
        summary = "Invalid model choice."
    return summary

iface = gr.Interface(
    fn=summarize,
    inputs=[
        gr.Textbox(lines=7, label="Enter text to summarize"),
        gr.Dropdown(choices=[
            "T5-small (Encoder-Decoder Transformer)",
            "GPT-2 small (Decoder-only Transformer)"
        ], label="Choose model")
    ],
    outputs=gr.Textbox(lines=7, label="Summary"),
    title="Multi-model Text Summarizer",
    description="Enter text and select a model to generate summary"
)

iface.launch()